version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: runnerz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
